src/backend/.filebrowser.json, src/backend/cmd/config_init.go, src/backend/cmd/root.go, src/backend/frontend/dist/.gitignore, src/backend/search/conditions.go, src/backend/search/indexing.go
=> make more efficient

.gitignore, CHANGELOG.md, README.md, backend/frontend/dist, backend/frontend/dist/.gitignore, backend/search/conditions.go, backend/version/version.go, frontend/package-lock.json, frontend/package.json, frontend/public/themes/dark.css, frontend/src/components/ButtonGroup.vue, frontend/src/components/Search.vue, frontend/src/components/Sidebar.vue, frontend/src/components/header/HeaderBar.vue, frontend/src/components/prompts/Prompts.vue, frontend/src/css/_share.css, frontend/src/css/base.css, frontend/src/css/dashboard.css, frontend/src/css/header.css, frontend/src/css/mobile.css, frontend/src/css/styles.css, frontend/src/views/files/Listing.vue
=> v0.1.3 updated styling

backend/search/indexing.go, frontend/src/components/Search.vue, frontend/src/components/Sidebar.vue, frontend/src/css/base.css, frontend/src/css/header.css, frontend/src/css/styles.css
=> updated a bit

README.md, backend/benchmark_results.txt, backend/settings/settings_test.go, backend/storage/bolt/config.go, roadmap.md
=> Updated readme and roadmap

frontend/src/css/_buttons.css, frontend/src/css/_inputs.css, frontend/src/css/_share.css, frontend/src/css/dashboard.css, frontend/src/css/listing.css
=> updated with rounded corners

backend/settings/config_test.go
=> updated test

Dockerfile, backend/cmd/root.go, backend/filebrowser.yaml, backend/settings/config.go, backend/users/storage.go, frontend/src/css/dark.css, frontend/src/css/listing.css, frontend/src/views/Layout.vue, roadmap.md
=> Update Dockerfile , settings, and tweaks

backend/benchmark_results.txt, backend/http/search.go, backend/index/conditions.go, backend/index/search_index.go, backend/index/search_index_test.go, frontend/src/api/utils.js
=> final Bugfix search

backend/filebrowser.yaml, backend/index/indexing.go, backend/index/indexing_test.go, backend/index/search_index.go, backend/index/search_index_test.go
last fix expected "/" at the beginning of the path, but that wasn't what the ui expected to see. So this changes that back
=> bugfix on search results view on ui

.github/workflows/pr-merge.yaml, CHANGELOG.md, backend/benchmark_results.txt, backend/filebrowser.yaml, backend/go.mod, backend/go.sum, backend/http/search.go, backend/index/indexing.go, backend/index/indexing_test.go, backend/index/search_index.go, backend/index/search_index_test.go
=> Updated with directory 2

backend/benchmark_results.txt, backend/filebrowser.yaml, backend/index/indexing.go
=> Fix index io

CHANGELOG.md, backend/cmd/root.go, backend/filebrowser.yaml, backend/files/conditions.go, backend/files/file.go, backend/files/indexing.go, backend/files/indexing_test.go, backend/files/listing.go, backend/files/search_index.go, backend/files/search_index_test.go, backend/files/sorting.go, backend/http/search.go, backend/index/indexing.go, backend/settings/config.go
an important update that makes browsing the webpage use the index for faster browsing.
=> Prep for use index for browsing

backend/files/file.go, backend/files/sync.go, backend/http/preview.go
=> Update file reading

backend/files/file.go, backend/files/sync.go, backend/http/preview.go
Reverts gtsteffaniak/filebrowser#79
=> Revert "Update file reading"

backend/http/search.go, frontend/src/components/settings/UserForm.vue, frontend/src/views/settings/Global.vue, frontend/src/views/settings/Profile.vue, frontend/src/views/settings/User.vue
=> Fix context for search

CHANGELOG.md, backend/filebrowser.yaml, backend/files/indexing.go, backend/files/search.go, backend/files/search_test.go, backend/http/search.go, frontend/package-lock.json, frontend/package.json, frontend/src/components/Search.vue
=> updated with context changes

frontend/src/css/dark.css, frontend/src/views/files/Listing.vue
=> Hide dotfile tweak

CHANGELOG.md, frontend/src/components/Search.vue, frontend/src/components/Sidebar.vue, frontend/src/components/prompts/Copy.vue, frontend/src/components/prompts/Delete.vue, frontend/src/components/prompts/Download.vue, frontend/src/components/prompts/FileList.vue, frontend/src/components/prompts/Move.vue, frontend/src/components/prompts/NewDir.vue, frontend/src/components/prompts/Prompts.vue, frontend/src/components/prompts/Replace.vue, frontend/src/components/prompts/ReplaceRename.vue, frontend/src/components/prompts/ShareDelete.vue, frontend/src/store/getters.js, frontend/src/store/index.js, frontend/src/store/mutations.js, frontend/src/views/Files.vue, frontend/src/views/Layout.vue, frontend/src/views/files/Listing.vue, frontend/src/views/files/Preview.vue, frontend/src/views/settings/User.vue
this pr is mostly based on https://github.com/filebrowser/filebrowser/pull/2667/
=> Feature added create on move

CHANGELOG.md, backend/auth/hook.go, backend/benchmark_results.txt, backend/cmd/root.go, backend/filebrowser.yaml, backend/files/file.go, backend/files/sync.go, backend/http/data.go, backend/http/public.go, backend/http/public_test.go, backend/http/raw.go, backend/http/share.go, backend/http/utils.go, backend/runner/runner.go, frontend/src/api/pub.js, frontend/src/api/utils.js, frontend/src/components/Breadcrumbs.vue, frontend/src/components/Search.vue, frontend/src/components/header/Action.vue, frontend/src/components/prompts/Copy.vue, frontend/src/components/prompts/FileList.vue, frontend/src/components/prompts/Move.vue, frontend/src/components/prompts/Share.vue, frontend/src/css/base.css, frontend/src/css/dark.css, frontend/src/css/listing.css, frontend/src/css/styles.css, frontend/src/views/Share.vue, frontend/src/views/files/Editor.vue, roadmap.md
- Feature: playable shared video
- Feature: photos and videos get embedded preview on share instead of icon
- FIX: sharable link bug, now uses publicUser with rules
=> updated share link behavior

CHANGELOG.md, README.md, backend/filebrowser.yaml, backend/http/public.go, backend/http/share.go, frontend/src/api/pub.js, frontend/src/api/users.js, frontend/src/api/utils.js, frontend/src/main.js, frontend/src/store/mutations.js, frontend/src/views/Share.vue, frontend/src/views/bars/ListingBar.vue, roadmap.md
=> make frontend api calls work

backend/filebrowser.yaml, backend/files/conditions.go, backend/files/file.go, backend/http/resource.go, frontend/src/api/files.js, frontend/src/views/Files.vue, frontend/src/views/Layout.vue, frontend/src/views/Share.vue, frontend/src/views/files/ListingView.vue
- adds audio on the share screen preview
- Uses the editor view mode for any files that have readable text content. (for example, anything not called "something.txt")
=> updated with more features!

.github/workflows/dev.yaml, .github/workflows/main.yaml, .github/workflows/pr-merge.yaml, .github/workflows/release.yaml
=> Update github actions

.github/workflows/dev.yaml, .github/workflows/main.yaml, .github/workflows/pr-merge.yaml, .github/workflows/release.yaml
=> Change github lint backend workflow

frontend/vite.config.ts
=> changed compression targets

backend/filebrowser.yaml, backend/http/static.go, frontend/package-lock.json, frontend/public/index.html, frontend/src/api/users.js, frontend/src/components/prompts/Share.vue, frontend/src/css/base.css, frontend/src/css/fonts.css, frontend/src/css/styles.css, frontend/src/i18n/index.ts, frontend/src/store/mutations.js, frontend/src/utils/moment.js, frontend/src/utils/url.js, frontend/src/views/Files.vue, frontend/src/views/Layout.vue, frontend/src/views/Login.vue, frontend/src/views/Share.vue, frontend/src/views/bars/Default.vue, frontend/src/views/settings/Profile.vue
=> fix url path

backend/files/file.go, backend/http/resource.go, frontend/src/api/users.js, frontend/src/api/utils.js, frontend/src/components/Breadcrumbs.vue, frontend/src/components/prompts/Copy.vue, frontend/src/components/prompts/DeleteUser.vue, frontend/src/components/prompts/Move.vue, frontend/src/components/prompts/NewFile.vue, frontend/src/components/settings/UserForm.vue, frontend/src/notify/message.js, frontend/src/store/getters.js, frontend/src/utils/moment.js, frontend/src/views/Layout.vue, frontend/src/views/bars/Default.vue, frontend/src/views/files/Editor.vue, frontend/src/views/settings/Global.vue, frontend/src/views/settings/Shares.vue, frontend/src/views/settings/User.vue, frontend/src/views/settings/Users.vue
=> updated when editor content empty

frontend/src/api/utils.js, frontend/src/components/prompts/Delete.vue, frontend/src/components/prompts/Download.vue, frontend/src/components/prompts/Share.vue, frontend/src/css/base.css, frontend/src/notify/index.ts, frontend/src/notify/message.js, frontend/src/store/getters.js, frontend/src/utils/buttons.js, frontend/src/views/Layout.vue, frontend/src/views/Share.vue, frontend/src/views/bars/ListingBar.vue, frontend/src/views/files/ListingView.vue
=> Improve notification styling & fix download links

backend/filebrowser.yaml
=> updated default config

frontend/src/components/ButtonGroup.vue, frontend/src/components/Search.vue
=> updated search behavior

CHANGELOG.md, README.md, roadmap.md
=> updated readme

frontend/src/api/users.js, frontend/src/components/Search.vue, frontend/src/components/Sidebar.vue, frontend/src/store/getters.js, frontend/src/store/mutations.js, frontend/src/store/state.js, frontend/src/views/Layout.vue
=> fixed overlay bug for mobile

frontend/src/api/users.js, frontend/src/components/Search.vue, frontend/src/components/Sidebar.vue, frontend/src/store/getters.js, frontend/src/store/mutations.js, frontend/src/store/state.js, frontend/src/views/Layout.vue
=> Updated ismobile fix

frontend/src/components/Search.vue
=> ismobile fix

backend/.goreleaser.yaml
=> added go-releaser config

frontend/src/components/Search.vue, frontend/src/components/Sidebar.vue, frontend/src/store/getters.js
=> updated state fix

.github/workflows/pr.yaml, .github/workflows/release.yaml, Dockerfile, Dockerfile.playwright, backend/cmd/users_import.go, backend/diskcache/file_cache_test.go, backend/files/file.go, backend/http/raw.go, backend/http/resource.go, backend/runner/runner.go, backend/users/storage.go, backend/users/users.go, backend/version/version.go, frontend/playwright.config.ts, frontend/src/components/prompts/Delete.vue, frontend/src/components/prompts/Move.vue, frontend/src/components/prompts/ReplaceRename.vue, frontend/test-results/.last-run.json
=> changed permissions and backend requirements

CHANGELOG.md, README.md, frontend/src/components/Sidebar.vue, frontend/src/store/getters.js, frontend/src/store/mutations.js, frontend/src/store/state.js, roadmap.md
sidebar should remember the sticky state
=> updated sidebar behavior

.github/workflows/main.yaml, .github/workflows/pr.yaml, Dockerfile, backend/.goreleaser.yaml, backend/http/static.go, backend/version/version.go, frontend/src/App.vue, frontend/src/components/Sidebar.vue, frontend/src/store/getters.js, frontend/src/utils/constants.js, makefile
=> Goreleaser versioning and docker versioning

README.md
=> Update readme comparison

backend/files/file.go, backend/files/search.go, backend/http/public.go, backend/http/raw.go, backend/http/resource.go, frontend/src/api/search.js, frontend/src/components/Search.vue, frontend/src/components/files/ExtendedImage.vue, frontend/src/components/sidebar/General.vue, frontend/src/router/index.ts
=> Update search behavior

CHANGELOG.md, frontend/src/components/FileSelection.vue, frontend/src/components/Search.vue, frontend/src/components/files/ExtendedImage.vue, frontend/src/components/sidebar/Sidebar.vue, frontend/src/store/getters.js, frontend/src/utils/download.js, frontend/src/views/Errors.vue, frontend/src/views/files/Editor.vue, frontend/src/views/files/ListingView.vue, frontend/src/views/files/Preview.vue
=> updated logic

.github/workflows/pr.yaml, .github/workflows/release.yaml
=> updated workflow

.github/workflows/main.yaml, backend/files/indexing.go, frontend/src/views/files/ListingView.vue
=> Hotfix v0.2.9

backend/files/sync.go, frontend/src/views/files/ListingView.vue
=> Adjusted path tweak

frontend/src/components/files/ListingItem.vue, frontend/src/store/mutations.js, frontend/src/views/bars/Default.vue, frontend/src/views/files/ListingView.vue
fixes https://github.com/gtsteffaniak/filebrowser/issues/214
=> fixed multiple selection clicking

CHANGELOG.md, backend/files/conditions.go, backend/files/file.go, backend/files/indexing.go, backend/files/search.go, backend/files/search_test.go, frontend/src/components/Search.vue
=> updated search

CHANGELOG.md, frontend/src/components/files/ListingItem.vue, frontend/src/views/files/ListingView.vue
allow direct right click actions.
This makes it much faster and easier to action single items and described on https://github.com/gtsteffaniak/filebrowser/issues/214
=> allow direct right click

CHANGELOG.md, backend/http/middleware.go, backend/http/public.go, backend/http/resource.go, backend/http/router.go, backend/http/share.go, backend/storage/bolt/share.go, backend/swagger/docs/docs.go, backend/swagger/docs/swagger.json, backend/swagger/docs/swagger.yaml, backend/users/users.go, frontend/src/api/share.js, frontend/src/api/utils.js, frontend/src/components/Breadcrumbs.vue, frontend/src/components/prompts/Share.vue, frontend/src/css/dashboard.css, frontend/src/store/getters.js, frontend/src/views/Settings.vue
=> Fix share router

backend/files/search_test.go
=> updated test order

backend/http/users.go, frontend/src/api/files.js, frontend/src/api/share.js, frontend/src/api/users.js, frontend/src/api/utils.js, frontend/src/notify/message.js, frontend/src/views/Settings.vue
last minute change introduced an api issue when creating users from settings.
=> Hotfix: user creation and other api url issues

README.md, backend/files/search_test.go, backend/http/users.go, frontend/src/api/files.js, frontend/src/api/share.js, frontend/src/api/users.js, frontend/src/api/utils.js, frontend/src/notify/message.js, frontend/src/views/Settings.vue
hotfix for user creation issue
=> Hotfix create user routing

frontend/src/router/index.ts, frontend/src/utils/auth.js, frontend/src/views/Login.vue
=> removed unnecessary api call to self every route change

.github/workflows/regular-tests.yaml, CHANGELOG.md, backend/cmd/root.go, backend/files/conditions.go, backend/files/file.go, backend/files/indexing.go, backend/files/indexing_test.go, backend/files/search.go, backend/files/search_test.go, backend/files/sync.go, backend/files/sync_test.go, backend/http/middleware.go, backend/http/middleware_test.go, backend/http/resource.go, backend/http/router.go, backend/settings/config.go, backend/settings/structs.go, backend/swagger/docs/docs.go, backend/swagger/docs/swagger.json, backend/swagger/docs/swagger.yaml, backend/utils/cache.go, backend/utils/main.go, backend/utils/main_test.go, docs/configuration.md, frontend/package.json, frontend/src/components/prompts/Delete.vue, frontend/src/store/getters.js, frontend/src/store/mutations.js, frontend/src/views/files/Editor.vue
=> Optimize response times

CHANGELOG.md, backend/files/conditions.go, backend/files/file.go, backend/files/indexing.go, backend/files/indexingFiles.go, backend/files/indexingSchedule.go, backend/files/indexing_test.go, backend/files/search.go, backend/files/search_test.go, backend/files/sync.go, backend/files/sync_test.go, backend/http/middleware_test.go, backend/http/preview.go, backend/http/public.go, backend/http/raw.go, backend/http/resource.go, backend/settings/config.go, backend/settings/structs.go, backend/swagger/docs/docs.go, backend/swagger/docs/swagger.json, backend/swagger/docs/swagger.yaml, docs/configuration.md, docs/indexing.md, frontend/src/api/utils.js, frontend/src/store/mutations.js, frontend/src/views/Files.vue, frontend/vite.config.ts.timestamp-1732411585993-fa353470e4284.mjs
=> Updated indexing and fixed bugs

backend/files/indexing_test.go, backend/files/mockIndexing.go, backend/http/middleware.go, backend/http/resource.go, backend/http/router.go, frontend/src/router/index.ts
=> Add compression

CHANGELOG.md, backend/http/middleware.go, frontend/src/components/Search.vue, frontend/src/router/index.ts, frontend/src/store/getters.js, frontend/src/store/mutations.js, frontend/src/utils/constants.js, frontend/src/utils/sort.test.js
noauth stopped working after v0.3.0 backend routes update
=> updated noauth bug

CHANGELOG.md, backend/img/service.go, frontend/src/api/files.js, frontend/src/components/ContextMenu.vue, frontend/src/components/Icon.vue, frontend/src/components/files/ListingItem.vue, frontend/src/components/prompts/Info.vue, frontend/src/router/index.ts, frontend/src/utils/index.ts, frontend/src/utils/url.js, frontend/src/views/Files.vue, frontend/src/views/Layout.vue, frontend/src/views/Share.vue, frontend/src/views/bars/Default.vue, frontend/src/views/files/ListingView.vue
=> updated with memory

CHANGELOG.md, frontend/src/components/Search.vue, frontend/src/components/files/ListingItem.vue, frontend/src/router/index.ts, frontend/src/views/Files.vue, frontend/src/views/files/ListingView.vue
=> Fix blocked input

CHANGELOG.md, README.md, backend/cmd/root.go, frontend/src/components/ContextMenu.vue, frontend/src/components/files/ListingItem.vue, frontend/src/views/files/ListingView.vue
=> more safari fixes... it behaves differently

frontend/src/components/files/ListingItem.vue, frontend/src/store/state.js, frontend/src/views/files/ListingView.vue
=> Fix touch events safari

CHANGELOG.md, frontend/src/components/ContextMenu.vue, frontend/src/components/files/ExtendedImage.vue, frontend/src/components/files/ListingItem.vue, frontend/src/css/listing.css, frontend/src/store/state.js, frontend/src/views/files/ListingView.vue, frontend/src/views/files/Preview.vue
=> Safari tweaks

CHANGELOG.md, backend/cmd/root.go, backend/config.yaml, backend/files/file.go, backend/files/indexingFiles.go, backend/files/indexingSchedule.go, backend/files/indexing_test.go, backend/files/search.go, backend/files/search_test.go, backend/files/sync.go, backend/files/sync_test.go, backend/go.mod, backend/http/preview.go, backend/http/resource.go, backend/http/search.go, backend/settings/config.go, backend/settings/structs.go, frontend/playwright.config.ts, frontend/src/components/Icon.vue, frontend/src/components/prompts/Upload.vue, frontend/src/views/files/ListingView.vue
=> Create sources loading

CHANGELOG.md, backend/auth/json.go, backend/auth/none.go, backend/auth/proxy.go, backend/files/file.go, backend/http/auth.go, backend/http/middleware.go, backend/http/public.go, backend/http/users.go, backend/settings/config.go, backend/storage/storage.go, frontend/src/components/Breadcrumbs.vue, frontend/src/components/ButtonGroup.vue, frontend/src/components/prompts/Rename.vue, frontend/src/components/settings/UserForm.vue, frontend/src/components/sidebar/General.vue, frontend/src/components/sidebar/Settings.vue, frontend/src/css/base.css, frontend/src/css/dark.css, frontend/src/store/mutations.js, frontend/src/utils/constants.js, frontend/src/views/settings/Profile.vue, frontend/src/views/settings/User.vue, frontend/src/views/settings/Users.vue
=> updated settings

.gitignore, CHANGELOG.md, Dockerfile, README.md, backend/.goreleaser.yaml, backend/settings/config.go, frontend/src/utils/sort.test.js, frontend/src/views/Login.vue, makefile
tweaks a few things to make using on windows a little bit easier. and tweaks a few styling things and cicd related operations.
=> Windows compatibility

frontend/src/components/settings/UserForm.vue, frontend/src/views/settings/User.vue, makefile
related to https://github.com/gtsteffaniak/filebrowser/discussions/274
The `!isNew` was missing from the user creation form.
=> fix user creation condition

.github/workflows/main.yaml, .github/workflows/pr.yaml, backend/files/indexingFiles.go, backend/files/indexing_test.go, backend/http/raw.go
fixes two issues:
1. windows path resolve issue for some interactions
2. zip and tar.gz file structure.
=> updated archiving structure

frontend/src/views/settings/User.vue
=> Fix user creation issue

backend/http/middleware.go, backend/settings/config.go, backend/settings/structs.go, backend/settings/testingConfig.yaml, frontend/src/views/settings/User.vue
=> updated with username in logs

backend/.goreleaser.yaml
=> updated go-releaser

CHANGELOG.md, backend/.goreleaser.yaml
=> updated changelog

CHANGELOG.md, backend/logger/setup.go, backend/logger/write.go, backend/settings/config.go
before:
```
2025/01/23 06:37:44 root.go:129: Using Config file        : test_config.yaml
2025/01/23 06:37:44 root.go:130: [DEBUG] Embeded frontend         : false
```
after:
```
2025/01/23 07:17:18 [INFO ] root.go:129: Using Config file        : test_config.yaml
2025/01/23 07:17:18 [DEBUG] root.go:130: Embeded frontend         : false
```
=> Tweak logging style

CHANGELOG.md, backend/files/file.go, backend/fileutils/file.go, backend/http/middleware.go, backend/http/resource.go, frontend/src/components/Search.vue, frontend/src/components/prompts/Copy.vue, frontend/src/components/prompts/Move.vue, frontend/src/utils/url.test.js
=> updated with search actions

CHANGELOG.md, backend/cmd/root.go, backend/logger/write.go, backend/settings/config.go, backend/settings/structs.go, frontend/src/components/Search.vue, frontend/tests/file-actions.spec.ts, frontend/tests/playwright-files/copyme.txt, frontend/tests/preview.spec.ts
more playwright = more stable
also fix sources issue
=> added more playwright tests

frontend/src/css/fonts.css, frontend/src/store/getters.js
fix a last minute find with the changes.
=> fix icons and download issue

frontend/src/views/bars/Default.vue, frontend/src/views/bars/EditorBar.vue, frontend/tests/file-actions.spec.ts, frontend/tests/preview.spec.ts
=> fixed history after preview

CHANGELOG.md, backend/docker-config.yaml, backend/http/auth.go, backend/http/middleware.go, backend/http/onlyOffice.go, backend/http/preview.go, backend/http/resource.go, backend/settings/config.go, backend/settings/structs.go, backend/settings/testingConfig.yaml, frontend/src/utils/constants.js, frontend/src/views/bars/Default.vue, frontend/src/views/settings/Global.vue
=> Deprecate old configs

CHANGELOG.md, backend/cmd/root.go, backend/files/sync.go, backend/http/auth.go, backend/http/middleware.go, backend/http/static.go, backend/logger/write.go, backend/settings/config.go, backend/settings/structs.go, backend/storage/bolt/users.go, backend/storage/storage.go
> Note: I changed the [config](https://github.com/gtsteffaniak/filebrowser/wiki/Configuration#example-auth-config) for password auth again... It was a mistake just to make it a boolean, so now you can provide options, going forward this allows for more.
**New Features**:
- password length requirement config via `auth.methods.password.minLength` as a number of characters required.
**Bugfixes**:
- NoAuth error message "resource not found" https://github.com/gtsteffaniak/filebrowser/issues/338
- CLI user configuration works and simplified see examples in the [Wiki](https://github.com/gtsteffaniak/filebrowser/wiki/CLI)
=> simple bugfixes beta/v0.5.1

CHANGELOG.md, frontend/src/views/bars/Default.vue
this is a bit of a workaround to onlyoffice library issue.
https://github.com/gtsteffaniak/filebrowser/issues/345
=> fixed only office close button issue.

CHANGELOG.md, backend/files/file.go, frontend/package.json, frontend/src/store/getters.js, frontend/src/store/mutations.js, frontend/src/store/state.js, frontend/src/views/Files.vue, frontend/src/views/Layout.vue, frontend/src/views/bars/Default.vue, frontend/src/views/bars/EditorBar.vue, frontend/src/views/files/MarkdownViewer.vue
=> updated with markdown viewer

backend/files/indexingFiles.go
=> respect fileEndsWith

CHANGELOG.md, README.md, backend/files/indexingFiles.go, backend/http/middleware.go, backend/http/raw.go, backend/settings/structs.go, backend/swagger/docs/docs.go, backend/swagger/docs/swagger.json, backend/swagger/docs/swagger.yaml, backend/users/users.go, frontend/src/components/Icon.vue, frontend/src/components/files/ListingItem.vue, frontend/src/components/prompts/Share.vue, frontend/src/css/base.css, frontend/src/css/listing.css, frontend/src/store/state.js, frontend/src/utils/mimetype.js, frontend/src/views/bars/Default.vue, frontend/src/views/settings/Profile.vue
=> Add easy download button

CHANGELOG.md, frontend/src/css/listing.css, frontend/src/views/bars/Default.vue, frontend/src/views/files/ListingView.vue, frontend/src/views/files/Preview.vue
=> updated with more tweaks

frontend/src/api/utils.js, frontend/src/api/utils.test.js, frontend/src/components/Search.vue, frontend/src/components/prompts/Copy.vue, frontend/src/components/prompts/Delete.vue, frontend/src/components/prompts/DeleteUser.vue, frontend/src/components/prompts/FileList.vue, frontend/src/components/prompts/Info.vue, frontend/src/components/prompts/Move.vue, frontend/src/components/prompts/Share.vue, frontend/src/store/getters.js, frontend/src/views/files/Editor.vue, frontend/tests/file-actions.spec.ts, frontend/tests/navigation.spec.ts
=> updated with filename with hash fix

CHANGELOG.md, backend/files/file.go, backend/http/middleware_test.go, backend/http/preview.go, frontend/src/api/utils.js, frontend/src/components/prompts/Delete.vue, frontend/src/components/prompts/Rename.vue, frontend/src/notify/loadingSpinner.js, frontend/src/utils/upload.js, frontend/src/views/Files.vue, frontend/src/views/bars/EditorBar.vue, frontend/src/views/files/ListingView.vue
=> updated with drag and drop fix

.github/workflows/main.yaml
=> updated playwright image

CHANGELOG.md, _docker/docker-compose.yaml, _docker/src/proxy/backend/config.yaml, _docker/src/proxy/backend/default.conf, backend/auth/hook.go, backend/http/api.go, backend/http/onlyOffice.go, backend/http/preview.go, backend/http/raw.go, backend/http/resource.go, backend/settings/config.go, backend/settings/settings.go, backend/swagger/docs/docs.go, backend/swagger/docs/swagger.json, backend/swagger/docs/swagger.yaml, backend/users/users.go, frontend/src/components/ContextMenu.vue, frontend/src/components/prompts/Copy.vue, frontend/src/components/prompts/Move.vue, frontend/src/components/settings/Permissions.vue, frontend/src/views/files/ListingView.vue
=> streamline permissions

backend/http/middleware.go
When a share is created and accessed via Public User the scope is set to "/does/not/exist" which leads to errors as scope is used in recreating the file path for the share. This commit sets it to default so that the file lookup points to the right location in storage. Some additional cleanup on variable redeclaration. Tested via creating, accessing and downloading a share.
=> shares: Fix local file paths for shares

CHANGELOG.md, backend/storage/bolt/users.go, frontend/src/components/prompts/NewDir.vue, frontend/src/utils/download.js, frontend/src/utils/files.js, frontend/src/utils/files.test.js, frontend/src/views/Files.vue, frontend/src/views/files/ListingView.vue, frontend/src/views/files/Preview.vue, frontend/tests/file-actions.spec.ts, frontend/tests/preview.spec.ts
=> add bugfixes for several issues

backend/config.yaml, backend/docker-config.yaml, backend/http/middleware.go, backend/http/onlyOffice.go, backend/http/preview.go, backend/http/public.go, backend/http/raw.go, backend/http/resource.go, backend/http/search.go, backend/http/share.go, backend/http/users.go, backend/settings/config.go, backend/share/share.go, backend/swagger/docs/docs.go, backend/swagger/docs/swagger.json, backend/swagger/docs/swagger.yaml, backend/utils/main.go, frontend/package.json, frontend/src/api/files.js, frontend/src/api/search.js, frontend/src/components/Breadcrumbs.vue, frontend/src/components/ContextMenu.vue, frontend/src/components/ProgressBar.vue, frontend/src/components/Search.vue, frontend/src/components/sidebar/General.vue, frontend/src/components/sidebar/Sidebar.vue, frontend/src/store/mutations.js, frontend/src/utils/url.js, frontend/src/views/Files.vue, frontend/src/views/files/Preview.vue
=> updated source issue

README.md, backend/http/public.go, backend/http/raw.go, backend/http/router.go, backend/http/share.go, backend/settings/config.go, backend/share/storage.go, backend/storage/bolt/share.go, backend/swagger/docs/docs.go, backend/swagger/docs/swagger.json, backend/swagger/docs/swagger.yaml, frontend/src/api/files.js, frontend/src/api/public.js, frontend/src/api/share.js, frontend/src/components/Breadcrumbs.vue, frontend/src/components/prompts/Share.vue, frontend/src/store/getters.js
=> resolve share link changes

backend/auth/hook.go, backend/cmd/root.go, backend/config.yaml, backend/http/auth.go, backend/http/middleware.go, backend/http/middleware_test.go, backend/http/public.go, backend/http/raw.go, backend/http/resource.go, backend/http/share.go, backend/storage/bolt/share.go, backend/storage/bolt/users.go, backend/storage/storage.go, backend/swagger/docs/docs.go, backend/swagger/docs/swagger.json, backend/swagger/docs/swagger.yaml, backend/users/storage.go, backend/users/users.go, frontend/src/api/public.js, frontend/src/components/Breadcrumbs.vue, frontend/src/components/ContextMenu.vue, frontend/src/components/Search.vue, frontend/src/components/prompts/Share.vue, frontend/src/components/sidebar/General.vue, frontend/src/components/sidebar/Sidebar.vue, frontend/tests/auth.spec.ts
=> Fix downloads share

CHANGELOG.md, backend/cmd/root.go, backend/files/file.go, backend/fileutils/file.go, backend/http/resource.go, backend/settings/config.go, frontend/src/components/prompts/Move.vue, frontend/src/utils/upload.js
**BugFixes**:
- fix conflict resolution issue https://github.com/gtsteffaniak/filebrowser/issues/384
=> updated with copy fix

CHANGELOG.md, README.md, backend/files/file.go, backend/files/indexing_test.go, backend/files/sync.go, backend/files/user.go, backend/http/onlyOffice.go, backend/http/preview.go, backend/http/raw.go, backend/http/resource.go, backend/http/search.go, frontend/src/components/Search.vue, frontend/src/components/prompts/Prompts.vue, frontend/src/components/prompts/ShareDelete.vue, frontend/src/components/settings/UserForm.vue, frontend/src/i18n/en.json, frontend/src/views/Settings.vue, frontend/src/views/files/ListingView.vue, frontend/src/views/settings/Shares.vue, frontend/src/views/settings/User.vue
=> Last minute changes

CHANGELOG.md, _docker/src/regular/backend/config.yaml, backend/cmd/root.go, backend/files/file.go, backend/http/public.go, backend/http/resource.go, backend/settings/config.go, backend/swagger/docs/docs.go, backend/swagger/docs/swagger.json, backend/swagger/docs/swagger.yaml, frontend/src/api/files.js, frontend/src/components/prompts/Copy.vue, frontend/src/components/prompts/Delete.vue, frontend/src/components/prompts/Move.vue, frontend/src/views/files/ListingView.vue, frontend/src/views/files/OnlyOfficeEditor.vue, frontend/src/views/files/Preview.vue, frontend/tests/auth.spec.ts, frontend/tests/file-actions.spec.ts, frontend/tests/preview.spec.ts
fixes last minute changes, enables env var for config file
=> updated source configs

.github/workflows/release_beta.yaml
=> updated name

CHANGELOG.md, backend/http/onlyOffice.go, backend/http/static.go, frontend/src/api/files.js, frontend/src/views/files/OnlyOfficeEditor.vue
bugfix for 0.6.0 and only office, since the raw URL needs source defined.
https://github.com/gtsteffaniak/filebrowser/issues/418
=> onlyoffice fix in 0.6.x

CHANGELOG.md, frontend/src/components/Breadcrumbs.vue, frontend/tests/navigation.spec.ts, frontend/tests/playwright-files/files/fortesting.md
fix bug -- trimming files from path https://github.com/gtsteffaniak/filebrowser/issues/419
=> fix breadcrumbs 

backend/settings/settings.go, backend/storage/storage.go, frontend/src/components/settings/UserForm.vue, frontend/tests/navigation.spec.ts
=> updated user defaults

CHANGELOG.md, _docker/Dockerfile, backend/config.yaml, backend/files/file.go, backend/files/indexingFiles.go, backend/files/indexing_test.go, backend/files/search.go, backend/files/sync.go, backend/files/sync_test.go, backend/http/middleware.go, backend/http/raw.go, backend/http/resource.go, backend/storage/storage.go, frontend/src/api/files.js, frontend/src/components/files/ListingItem.vue, frontend/src/utils/mimetype.js, frontend/src/views/files/ListingView.vue, frontend/src/views/files/Preview.vue
optimize download and update paths.
adds debugging message for users downloading files:
`2025/03/11 09:36:55 [DEBUG] raw.go:236: User admin is downloading large (540 MB) file: myfile.zip`
=> File download ram issue

.github/workflows/pr.yaml, backend/files/file.go, backend/fileutils/file.go, backend/http/resource.go, frontend/src/api/files.js, frontend/src/components/Breadcrumbs.vue, frontend/src/components/files/ListingItem.vue, frontend/src/views/Files.vue, frontend/src/views/files/ListingView.vue, frontend/tests/navigation.spec.ts
simplified the breadcrumbs and make sure it works as expected for all folder types.
=> updated breadcrumbs a bit more

frontend/tests/navigation.spec.ts
=> updated playwright test

makefile
=> Update makefile (#445)

backend/http/middleware.go, frontend/src/api/public.js, frontend/src/api/share.js, frontend/src/components/Breadcrumbs.vue, frontend/src/components/files/ListingItem.vue, frontend/src/components/prompts/Share.vue, frontend/src/router/index.ts
=> updated with more share fixes

CHANGELOG.md, backend/cmd/user.go, backend/files/user.go, backend/storage/bolt/users.go, frontend/src/components/prompts/Share.vue, frontend/src/views/files/Preview.vue
=> fixed issues for 0.6.x

CHANGELOG.md, README.md, backend/cmd/user.go, backend/database/storage/bolt/users.go, frontend/src/views/files/Preview.vue, makefile, package-lock.json
=> Merge from main

backend/http/public.go, backend/http/raw.go
=> updated with share download fix

backend/http/public.go, frontend/src/api/files.js, frontend/src/api/public.js, frontend/src/utils/download.js, frontend/src/views/Share.vue
=> more share fixes

CHANGELOG.md, _docker/src/proxy/backend/config.yaml, backend/auth/hook.go, backend/http/middleware.go, backend/http/public.go, backend/http/share.go, backend/settings/config.go, backend/settings/settings.go, backend/settings/structs.go, frontend/src/components/sidebar/General.vue, frontend/src/router/index.ts, frontend/src/utils/url.test.js
=> updated with proxy user fix

backend/files/sync.go, backend/http/middleware.go, backend/http/share.go, frontend/tests-playwright/general/share.spec.ts, frontend/tests-playwright/global-setup.ts, makefile
shares recently stopped working for individual files
=> updated file share link behavior for files

_docker/Dockerfile
related to https://github.com/gtsteffaniak/filebrowser/issues/497
=> updated docker directory perms

.dockerignore, .gitignore, CHANGELOG.md, _docker/Dockerfile, backend/auth/hook.go, backend/files/sync.go, backend/http/middleware.go, backend/http/public.go, backend/http/raw.go, backend/http/share.go, backend/settings/config.go, backend/settings/settings.go, backend/settings/structs.go, backend/swagger/docs/docs.go, backend/swagger/docs/swagger.json, backend/swagger/docs/swagger.yaml, frontend/src/api/files.js, frontend/src/api/public.js, frontend/src/api/share.js, frontend/src/components/files/ListingItem.vue, frontend/src/components/sidebar/General.vue, frontend/src/router/index.ts, frontend/src/utils/download.js, frontend/src/utils/url.test.js, frontend/src/views/Share.vue, frontend/tests-playwright/general/share.spec.ts, frontend/tests-playwright/global-setup.ts, makefile
=> Update docker perms

CHANGELOG.md, _docker/src/noauth/frontend/playwright.config.ts, _docker/src/proxy/backend/config.yaml, _docker/src/proxy/backend/default.conf, backend/files/search.go, backend/files/search_test.go, frontend/src/api/files.js, frontend/src/components/Search.vue, frontend/src/utils/url.js, frontend/tests-playwright/noauth-setup.ts, frontend/tests-playwright/noauth/file-actions.spec.ts, frontend/tests-playwright/noauth/navigation.spec.ts, frontend/tests-playwright/noauth/share.spec.ts, frontend/tests-playwright/noauth/theme-branding.spec.ts, makefile
=> updated with fix

CHANGELOG.md, backend/cmd/user.go, backend/common/settings/auth.go, backend/common/settings/structs.go, backend/database/storage/bolt/users.go, backend/database/users/users.go, backend/http/auth.go, backend/http/middleware.go, backend/http/preview.go, backend/http/router.go, backend/http/static.go, backend/preview/image.go, backend/preview/preview.go, backend/swagger/docs/docs.go, backend/swagger/docs/swagger.json, backend/swagger/docs/swagger.yaml, frontend/src/components/settings/UserForm.vue, frontend/src/store/state.js, frontend/src/utils/constants.js, frontend/src/views/Login.vue, frontend/src/views/settings/User.vue, frontend/src/views/settings/Users.vue
=> updated with oidc login

CHANGELOG.md, _docker/src/noauth/backend/config.yaml, _docker/src/proxy/backend/config.yaml, backend/config.yaml, backend/files/file.go, backend/http/auth.go, backend/http/middleware.go, backend/http/middleware_test.go, backend/http/raw.go, backend/http/static.go, backend/logger/write.go, backend/settings/config.go, backend/settings/config_test.go, backend/settings/structs.go, backend/utils/main.go, frontend/tests-playwright/general/file-actions.spec.ts, makefile
=> Update validations v0.6.8

CHANGELOG.md, backend/settings/structs.go
=> Disable bool validation

backend/settings/structs.go
=> sync validation change with beta v0.6.8

CHANGELOG.md, _docker/Dockerfile.playwright-proxy, _docker/src/proxy/backend/default.conf, backend/adapters/fs/files/files.go, backend/common/utils/main.go, backend/database/storage/bolt/users.go, backend/http/auth.go, backend/http/middleware.go, backend/http/resource.go, backend/indexing/indexingFiles.go, backend/indexing/iteminfo/conditions.go, frontend/src/components/files/Icon.vue, frontend/src/components/prompts/Upload.vue, frontend/src/components/settings/UserForm.vue, frontend/src/css/listing.css, frontend/src/utils/upload.js, frontend/src/utils/url.js, frontend/src/views/files/ListingView.vue
=> updated with more fixes

CHANGELOG.md, backend/cmd/user.go, backend/http/raw.go, backend/http/search.go, frontend/src/api/files.js, frontend/src/api/search.js, frontend/src/components/Action.vue, frontend/src/components/Search.vue, frontend/src/components/files/ListingItem.vue, frontend/src/router/index.ts, frontend/src/utils/auth.js, frontend/src/utils/download.js, frontend/src/utils/upload.js, frontend/src/views/Files.vue, frontend/src/views/Layout.vue, frontend/src/views/bars/Default.vue
=> Fix search scope

CHANGELOG.md, backend/cmd/office.go, backend/cmd/root.go, backend/common/settings/auth.go, backend/common/settings/config.go, backend/common/settings/settings.go, backend/common/settings/structs.go, backend/common/settings/validConfig.yaml, backend/http/auth.go, backend/http/onlyOffice.go, backend/http/preview.go, backend/preview/preview.go, backend/preview/video.go, backend/swagger/docs/docs.go, backend/swagger/docs/swagger.json, backend/swagger/docs/swagger.yaml, backend/tools/yaml.go, frontend/src/api/files.js, frontend/src/api/public.js, frontend/src/notify/events.js, frontend/src/router/index.ts, frontend/src/store/mutations.js, frontend/src/views/settings/Profile.vue, makefile
=> More final changes

.github/workflows/tag.yaml, backend/swagger/docs/docs.go, backend/swagger/docs/swagger.json, backend/swagger/docs/swagger.yaml
=> Merged changes

.github/workflows/tag.yaml, _docker/Dockerfile, _docker/Dockerfile.media
fix some v0.7.0 workflow changes
=> Workflow update

CHANGELOG.md, backend/http/auth.go, frontend/src/components/Action.vue, frontend/src/components/files/PopupPreview.vue, frontend/src/components/sidebar/General.vue, frontend/src/store/mutations.js, frontend/src/store/state.js, frontend/src/views/bars/Default.vue
=> updated with more verbose debug level logs for oidc jwks

CHANGELOG.md, frontend/src/store/mutations.js, frontend/src/store/state.js
=> updated with multi button close hover fix

CHANGELOG.md, backend/adapters/fs/files/user.go, backend/common/logger/write.go, backend/database/storage/bolt/users.go, backend/http/auth.go, frontend/src/components/Action.vue, frontend/src/components/sidebar/General.vue, frontend/src/views/bars/Default.vue
=> revert enforced login method

backend/http/auth.go, frontend/src/views/bars/Default.vue
authelia requires redirect_uris, so adding that too
=> updated with small change

CHANGELOG.md, backend/adapters/fs/files/user.go, backend/common/logger/write.go, backend/database/storage/bolt/users.go, backend/http/auth.go, frontend/src/components/Action.vue, frontend/src/components/sidebar/General.vue, frontend/src/views/bars/Default.vue
=> revert enforced login method (#612)

backend/common/logger/write.go, backend/database/users/users.go, backend/http/preview.go, backend/preview/preview.go, backend/preview/video.go, backend/swagger/docs/docs.go, backend/swagger/docs/swagger.json, backend/swagger/docs/swagger.yaml, frontend/src/api/files.js, frontend/src/components/files/Icon.vue, frontend/src/views/settings/Profile.vue
=> add motion previews for videos

CHANGELOG.md, backend/cmd/user.go, backend/common/settings/auth.go, backend/common/settings/structs.go, backend/database/storage/bolt/users.go, backend/database/users/users.go, backend/http/auth.go, backend/swagger/docs/docs.go, backend/swagger/docs/swagger.json, backend/swagger/docs/swagger.yaml, backend/tools/yaml.go, frontend/src/components/files/Icon.vue, frontend/src/views/settings/Profile.vue
=> updated motion behavior

backend/common/settings/auth.go, backend/common/settings/config.go, backend/go.mod, backend/go.sum, backend/http/auth.go, backend/swagger/docs/docs.go, backend/swagger/docs/swagger.json, backend/swagger/docs/swagger.yaml
=> updated OIDC

CHANGELOG.md, backend/common/settings/auth.go, backend/http/auth.go, backend/http/httpRouter.go, backend/swagger/docs/docs.go, backend/swagger/docs/swagger.json, backend/swagger/docs/swagger.yaml, frontend/src/components/Action.vue, frontend/src/utils/auth.js, frontend/src/views/bars/Default.vue, frontend/src/views/files/OnlyOfficeEditor.vue
=> updated with logout

frontend/src/i18n/de.json
Updated some grammar and wording of the German translation.
=> Corrections to German translation

CHANGELOG.md, backend/database/storage/storage.go, frontend/src/components/files/ListingItem.vue, frontend/src/components/settings/UserForm.vue, frontend/src/views/bars/Default.vue, frontend/src/views/files/ListingView.vue, frontend/src/views/settings/User.vue, frontend/src/views/settings/Users.vue, frontend/tests-playwright/general/settings.spec.ts, frontend/tests-playwright/proxy/preview.spec.ts
=> updated with fix for create user

CHANGELOG.md, backend/database/storage/storage.go, frontend/src/components/files/ListingItem.vue, frontend/src/components/settings/UserForm.vue, frontend/src/views/bars/Default.vue, frontend/src/views/files/ListingView.vue, frontend/src/views/settings/User.vue, frontend/src/views/settings/Users.vue, frontend/tests-playwright/general/settings.spec.ts, frontend/tests-playwright/proxy/preview.spec.ts
**Notes**:
- Updated German translation. https://github.com/gtsteffaniak/filebrowser/pull/644
**BugFixes**:
- windows control click https://github.com/gtsteffaniak/filebrowser/issues/642
- create user issue https://github.com/gtsteffaniak/filebrowser/issues/647
=> updated with fix for create user (#649)

CHANGELOG.md, backend/adapters/fs/files/files.go, backend/go.mod, backend/go.sum, backend/swagger/docs/docs.go, backend/swagger/docs/swagger.json, backend/swagger/docs/swagger.yaml, frontend/package.json, frontend/public/config.generated.yaml, frontend/src/components/Breadcrumbs.vue, frontend/src/views/files/MarkdownViewer.vue
=> markdown preview enhancements

CHANGELOG.md, backend/cmd/cli.go, backend/http/preview.go
=> Add cli setup config

.github/workflows/release_dev.yaml, _docker/Dockerfile
=> updated dockerfile and workflow

.github/workflows/tag.yaml
=> updated tag release again

.github/workflows/tag.yaml, _docker/src/proxy/backend/config.yaml, backend/http/auth.go, frontend/src/components/files/Icon.vue, frontend/src/utils/auth.js
=> one more fix

.github/workflows/tag.yaml, _docker/Dockerfile, _docker/Dockerfile.slim, backend/.goreleaser.yaml, backend/common/settings/structs.go, backend/http/static.go, backend/indexing/iteminfo/conditions.go, backend/preview/preview.go, frontend/public/config.generated.yaml, frontend/src/components/files/Icon.vue, frontend/src/utils/constants.js, frontend/src/views/settings/Profile.vue, makefile
=> Build with cgo

.github/workflows/tag.yaml, backend/.goreleaser.yaml
=> Try all goreleasers

.github/workflows/tag.yaml
=> Change name

.github/workflows/tag.yaml, backend/.goreleaser.yaml
=> updated goreleaser

.dockerignore, .github/workflows/regular-tests.yaml, .github/workflows/tag.yaml, .gitignore, CHANGELOG.md, _docker/Dockerfile, _docker/Dockerfile.slim, backend/.goreleaser.yaml
=> Add zig cross compile

CHANGELOG.md, backend/http/preview.go, backend/preview/preview.go, frontend/public/config.generated.yaml, frontend/src/api/files.js, frontend/src/components/ContextMenu.vue, frontend/src/components/files/Icon.vue, frontend/src/utils/download.js, frontend/src/views/files/Preview.vue
=> add more preview options

CHANGELOG.md, backend/adapters/fs/diskcache/file_cache.go, backend/auth/json.go, backend/http/middleware.go, backend/http/oidc.go, backend/http/totp.go, backend/preview/preview.go, frontend/src/api/users.js, frontend/src/components/prompts/Copy.vue, frontend/src/components/prompts/FileList.vue, frontend/src/components/prompts/Move.vue, frontend/src/components/prompts/ReplaceRename.vue, frontend/src/components/prompts/Totp.vue, frontend/src/views/files/Editor.vue, frontend/tests-playwright/general/file-actions.spec.ts
=> updated with password login fixes

CHANGELOG.md, backend/preview/preview.go, frontend/src/components/ContextMenu.vue, frontend/src/store/getters.js, frontend/src/views/files/DocViewer.vue, frontend/src/views/files/Editor.vue, frontend/src/views/files/EpubViewer.vue, frontend/src/views/files/MarkdownViewer.vue
=> Empty image error

.github/workflows/tag.yaml, frontend/public/config.generated.yaml, frontend/src/api/users.js, frontend/src/views/files/Preview.vue
=> updated with pdf viewer

CHANGELOG.md, backend/http/raw.go, backend/http/resource.go, backend/http/search.go, backend/http/share.go, backend/indexing/indexingFiles.go, frontend/src/api/files.js, frontend/src/api/share.js, frontend/src/components/Search.vue, frontend/src/components/prompts/Info.vue, frontend/src/utils/url.js, frontend/src/views/files/ListingView.vue
=> More small fixes

backend/http/oidc.go, backend/indexing/indexingFiles.go
=> updated for main

CHANGELOG.md, backend/http/share.go
=> updated with share scope fix

backend/http/oidc.go, frontend/public/config.generated.yaml, frontend/src/router/index.ts
=> updated redirect

backend/http/auth.go, frontend/src/views/Login.vue
=> updated redirect login

backend/http/auth.go, frontend/src/components/settings/UserForm.vue, frontend/src/views/Login.vue
=> Allow admin reset otp

CHANGELOG.md, _docker/src/noauth/backend/config.yaml, backend/common/settings/config.go, backend/common/settings/generator.go, backend/common/settings/structs.go, backend/database/storage/storage.go, backend/http/resource.go, backend/indexing/indexingFiles.go, backend/indexing/indexingSchedule.go, backend/indexing/indexing_test.go, backend/swagger/docs/docs.go, backend/swagger/docs/swagger.json, backend/swagger/docs/swagger.yaml, frontend/public/config.generated.yaml, frontend/src/api/files.js, frontend/src/components/ContextMenu.vue, frontend/src/components/prompts/Share.vue, frontend/src/utils/upload.js
=> Upload files bug

backend/http/resource.go, frontend/src/api/files.js, frontend/src/components/Breadcrumbs.vue, frontend/src/components/Search.vue, frontend/src/components/prompts/NewDir.vue, frontend/src/components/prompts/NewFile.vue, frontend/src/views/Errors.vue, frontend/src/views/files/Preview.vue
=> File upload

backend/common/settings/structs.go, backend/swagger/docs/docs.go, backend/swagger/docs/swagger.json, backend/swagger/docs/swagger.yaml, frontend/public/config.generated.yaml
relates to https://github.com/gtsteffaniak/filebrowser/issues/872
=> fix typo in json annotation

backend/common/settings/structs.go, backend/swagger/docs/docs.go, backend/swagger/docs/swagger.json, backend/swagger/docs/swagger.yaml, frontend/public/config.generated.yaml
relates to https://github.com/gtsteffaniak/filebrowser/issues/872
=> annotations

CHANGELOG.md, backend/adapters/fs/files/files.go, backend/cmd/user_test.go, backend/common/settings/config.go, backend/common/settings/structs.go, backend/go.mod, backend/go.sum, backend/http/httpRouter.go, backend/http/middleware.go, backend/http/onlyOffice.go, backend/http/preview.go, backend/http/public.go, backend/http/resource.go, backend/http/search.go, backend/http/share.go, backend/swagger/docs/docs.go, backend/swagger/docs/swagger.json, backend/swagger/docs/swagger.yaml, frontend/public/config.generated.yaml
=> updated without default source

CHANGELOG.md, backend/common/settings/structs.go, backend/database/users/users.go, backend/http/static.go, backend/indexing/indexingFiles.go, backend/swagger/docs/docs.go, backend/swagger/docs/swagger.json, backend/swagger/docs/swagger.yaml, frontend/public/config.generated.yaml, frontend/src/components/ContextMenu.vue, frontend/src/components/Search.vue, frontend/src/components/sidebar/General.vue, frontend/src/i18n/en.json, frontend/src/store/mutations.js, frontend/src/utils/constants.js, frontend/src/utils/sort.js, frontend/src/utils/sort.test.js, frontend/src/views/bars/Default.vue, frontend/src/views/files/ListingView.vue, frontend/src/views/settings/Profile.vue
=> Minimal UI

backend/adapters/fs/files/files.go, backend/cmd/cli.go, backend/go.mod, backend/go.sum, backend/indexing/checkLinuxStub.go, backend/indexing/checkWindows.go, backend/indexing/mutate.go, frontend/public/config.generated.yaml, frontend/src/api/files.js, frontend/src/components/sidebar/General.vue, frontend/src/store/mutations.js, frontend/src/utils/upload.js, frontend/src/views/files/ListingView.vue, frontend/src/views/settings/Profile.vue, frontend/tests-playwright/general/share.spec.ts, frontend/tests-playwright/noauth/share.mobile.spec.ts, frontend/tests-playwright/noauth/share.spec.ts, frontend/tests-playwright/test-setup.ts
=> Tweak some changes

CHANGELOG.md, backend/adapters/fs/files/files.go, frontend/src/i18n/en.json, frontend/src/utils/upload.js, frontend/src/views/Files.vue, frontend/src/views/Layout.vue
=> updated upload behavior

backend/common/settings/auth.go, backend/http/oidc.go, backend/http/oidc_test.go, backend/swagger/docs/swagger.json, backend/swagger/docs/swagger.yaml, frontend/public/config.generated.yaml
Add a setting for user groups oidc claim; see https://github.com/gtsteffaniak/filebrowser/issues/934
=> Add a setting for user groups oidc claim

CHANGELOG.md, backend/indexing/iteminfo/conditions.go, frontend/src/components/Search.vue, frontend/src/components/prompts/Delete.vue, frontend/src/components/prompts/Upload.vue, frontend/src/views/Files.vue, frontend/src/views/bars/Default.vue, frontend/src/views/files/Preview.vue
=> updated with trailing slash fix

CHANGELOG.md, backend/indexing/checkLinuxStub.go
=> update partition size

backend/common/settings/config.go, frontend/public/config.generated.yaml, frontend/public/index.html, frontend/src/css/base.css
Added 
```
body {
background-color: {{ .LightBackground }};
}
```
This solves #1021 with setting the background on Light mode via the config file.
=> LightBackground bugfix

.github/workflows/pr.yaml, CHANGELOG.md, _docker/Dockerfile.playwright-general, _docker/Dockerfile.playwright-noauth, _docker/Dockerfile.playwright-proxy, _docker/Dockerfile.primecache, _docker/src/general/frontend/playwright.config.ts, _docker/src/noauth/frontend/playwright.config.ts, backend/cmd/cli.go, backend/database/storage/bolt/users.go, backend/database/storage/storage.go, backend/http/auth.go, backend/http/oidc.go, backend/http/users.go, frontend/src/components/Tooltip.vue, frontend/src/components/prompts/DeleteUser.vue, frontend/tests-playwright/general/settings.spec.ts, frontend/tests-playwright/general/theme-branding.spec.ts, frontend/tests-playwright/general/user-actions.spec.ts, frontend/tests-playwright/global-setup.ts, frontend/tsconfig.json
=> fix save user issue

CHANGELOG.md, _docker/src/general/frontend/playwright.config.ts, backend/common/settings/config.go, backend/indexing/indexingFiles.go, frontend/public/config.generated.yaml, frontend/src/components/files/Icon.vue, frontend/src/components/files/ListingItem.vue, frontend/src/components/sidebar/General.vue, frontend/src/css/listing.css, frontend/src/utils/eventBus.js
=> updated counting

.github/workflows/pr.yaml, _docker/Dockerfile.playwright-base, _docker/Dockerfile.playwright-general, _docker/Dockerfile.playwright-oidc, _docker/src/oidc/backend/config.yaml, _docker/src/oidc/frontend/mock-oidc-server.js, _docker/src/oidc/frontend/playwright.config.ts, backend/common/settings/auth.go, frontend/package.json, frontend/tests-playwright/oidc-setup.ts, frontend/tests-playwright/oidc/preview.spec.ts, frontend/tests-playwright/types.d.ts, makefile
=> more tests cicd

frontend/src/css/listing.css
=> Fix gallery

CHANGELOG.md, backend/common/settings/structs.go, backend/database/access/access.go, backend/database/access/access_test.go, backend/http/access.go, backend/swagger/docs/docs.go, backend/swagger/docs/swagger.json, backend/swagger/docs/swagger.yaml, frontend/public/config.generated.yaml, frontend/src/components/Search.vue, frontend/src/components/prompts/Access.vue, frontend/src/components/prompts/CreateApi.vue, frontend/src/components/prompts/Delete.vue, frontend/src/components/prompts/FileList.vue, frontend/src/components/prompts/Password.vue, frontend/src/components/prompts/Prompts.vue, frontend/src/components/prompts/Share.vue, frontend/src/css/base.css, frontend/src/i18n/en.json, frontend/src/views/Files.vue, frontend/src/views/settings/Shares.vue
=> updated styling and tests

frontend/src/components/Search.vue, frontend/src/css/mobile.css
=> moved css to search component

CHANGELOG.md, backend/adapters/fs/files/files.go, backend/database/access/access.go
=> access management changes

CHANGELOG.md, backend/events/eventRouter.go, backend/http/httpEvents.go, backend/http/httpRouter.go, frontend/src/api/index.js, frontend/src/api/public.js, frontend/src/api/share.js, frontend/src/components/prompts/Share.vue, frontend/src/views/settings/Shares.vue
=> updated with changes for share

frontend/src/css/_variables.css, frontend/src/views/files/Editor.vue, frontend/src/views/settings/Shares.vue
=> editor reverted changes

backend/http/onlyOffice.go, frontend/src/views/files/OnlyOfficeEditor.vue, frontend/tests/playwright/proxy-setup.ts
=> updated debugging and scoped path

backend/cmd/cli.go
Noticed this typo while setting up filebrowser quantum on a new server.
=> Fix typo in Configuration Setup

CHANGELOG.md, backend/adapters/fs/files/files.go, backend/auth/totp.go, backend/common/settings/styling.go, backend/common/utils/cache.go, backend/database/access/access.go, backend/ffmpeg/subtitles.go, backend/go.mod, backend/go.sum, backend/http/onlyOffice.go, backend/indexing/indexingFiles.go, backend/indexing/mutate.go, backend/indexing/search.go
=> updated dependencies

CHANGELOG.md, backend/cmd/root.go, backend/common/settings/config.go, backend/common/settings/structs.go, backend/go.mod, backend/go.sum, backend/swagger/docs/docs.go, backend/swagger/docs/swagger.json, backend/swagger/docs/swagger.yaml, frontend/public/config.generated.yaml
=> added json logging support

CHANGELOG.md, backend/common/settings/auth.go
=> updated with better bot check

frontend/src/views/files/plyrViewer.vue
Hi, here making another pull.
I fixed/improved some styles of plyr:
- The play button (the big on the middle) was more "lower", uncentered? (sorry for my english)
Well, I fixed that, now is on the middle like on pc.
- fixed the buttons on video player (they were black), now is fine again.
- Also now when you use landscape mode on a phone the cover and some items don't will go out of the screen.
- Video player:
- Audio player:
=> Improve styles of plyr

.gitignore, CHANGELOG.md, backend/.goreleaser.yaml, backend/common/settings/config.go, backend/common/settings/generator.go, backend/common/settings/multiconfig_test.go, backend/common/settings/structs.go, backend/http/settings.go, backend/swagger/docs/docs.go, backend/swagger/docs/swagger.json, backend/swagger/docs/swagger.yaml, frontend/public/config.generated.yaml, frontend/src/views/settings/SystemAdmin.vue, makefile
=> updated with config adjustments

CHANGELOG.md, backend/auth/storage.go, backend/indexing/indexingFiles.go, backend/preview/preview.go
=> 2fa secret validation fix

backend/indexing/indexingFiles.go, backend/indexing/iteminfo/conditions.go, backend/indexing/iteminfo/mediaMeta.go
=> updated with performance improvements

CHANGELOG.md, frontend/src/components/prompts/Rename.vue, frontend/src/store/mutations.js
=> fixed rename issue

frontend/src/views/files/Editor.vue
This PR prevents accidental data loss in the file editor by introducing a confirmation prompt when a user tries to exit with unsaved changes. Currently, a user can edit a file and close the tab or navigate away without any warning, causing all modifications to be permanently lost.
This change implements the behavior suggested in issue #1241.
Now, the editor tracks if the content has been modified. If a user with unsaved changes attempts to leave the page, a confirmation dialog will appear, asking if they want to save their work before exiting.
Adds isDirty flag to track unsaved changes in the editor. Prompts the user to save changes before unmounting if there are unsaved edits. Refactors usage of req to originalReq for state synchronization and …
=> feat: Prompt to save on unsaved changes in editor
